/* eslint-disable */
// Code generated by scripts/generateErrorCodes.ts. DO NOT EDIT.
// Run `npm run generate:error-codes` after editing error_codes.yaml.

export interface ErrorCodeDefinition {
  code: string;
  domain: string;
  name: string;
  uiMessage: string;
  action: string | null;
}

export const ERROR_DEFINITIONS = {
  "E001": { code: "E001", domain: "diagnostics", name: "DIAGNOSTIC_NOT_FOUND", uiMessage: "指定した診断が見つかりません", action: "診断を選び直してください" },
  "E00100": { code: "E00100", domain: "common", name: "UNAUTHENTICATED", uiMessage: "管理者ログインが必要です", action: "ログインする" },
  "E00101": { code: "E00101", domain: "common", name: "PERMISSION_DENIED", uiMessage: "この画面へアクセスする権限がありません", action: "ダッシュボードへ戻る" },
  "E00102": { code: "E00102", domain: "common", name: "VALIDATION_ERROR", uiMessage: "入力内容に誤りがあります", action: "入力を修正する" },
  "E00103": { code: "E00103", domain: "common", name: "RESOURCE_NOT_FOUND", uiMessage: "対象データが見つかりません", action: "再読み込みする" },
  "E002": { code: "E002", domain: "diagnostics", name: "VERSION_NAME_DUP", uiMessage: "同じ版名がすでに存在します", action: "版名を変更してください" },
  "E00999": { code: "E00999", domain: "common", name: "UNEXPECTED_ERROR", uiMessage: "不明なエラーが発生しました", action: "しばらくして再試行" },
  "E010": { code: "E010", domain: "diagnostics", name: "VERSION_NOT_FOUND", uiMessage: "指定した版が見つかりません", action: "版一覧を再読み込みしてください" },
  "E011": { code: "E011", domain: "diagnostics", name: "STATUS_INVALID", uiMessage: "診断一覧の取得条件が不正です", action: "フィルタを確認する" },
  "E013": { code: "E013", domain: "diagnostics", name: "INVALID_FILTER", uiMessage: "クエリパラメータの組み合わせが不正です", action: "条件を確認してください" },
  "E020": { code: "E020", domain: "diagnostics", name: "VERSION_FROZEN", uiMessage: "指定した版は凍結されています", action: "Draft 版を選択してください" },
  "E030": { code: "E030", domain: "diagnostics", name: "DEP_MISSING", uiMessage: "必要な依存データが不足しています", action: "関連データを確認してください" },
  "E031": { code: "E031", domain: "diagnostics", name: "IMPORT_VALIDATION", uiMessage: "入力内容が不正です", action: "入力内容を確認してください" },
  "E033": { code: "E033", domain: "diagnostics", name: "SHEET_MISSING", uiMessage: "テンプレートに必須シートが含まれていません", action: "テンプレートを確認してください" },
  "E034": { code: "E034", domain: "diagnostics", name: "COL_MISSING", uiMessage: "テンプレートの列構成が一致しません", action: "テンプレートを確認してください" },
  "E10101": { code: "E10101", domain: "auth", name: "INVALID_CREDENTIALS", uiMessage: "ユーザー認証情報が無効です", action: "再度ログイン" },
  "E10113": { code: "E10113", domain: "auth", name: "USER_NOT_FOUND", uiMessage: "ユーザーが存在しません", action: "入力内容を確認" },
  "E10114": { code: "E10114", domain: "auth", name: "INVALID_TOKEN", uiMessage: "ユーザーセッションが期限切れです", action: "再ログインする" },
  "E11100": { code: "E11100", domain: "admin_auth", name: "INVALID_ADMIN_CREDENTIALS", uiMessage: "管理者 ID またはパスワードが正しくありません", action: "入力を確認する" },
  "E11101": { code: "E11101", domain: "admin_auth", name: "ADMIN_TOKEN_INVALID", uiMessage: "管理者セッションが期限切れです", action: "再ログインする" },
  "E11102": { code: "E11102", domain: "admin_auth", name: "ADMIN_TOKEN_SCOPE_INVALID", uiMessage: "必要な管理者権限がありません", action: "トップに戻る" },
  "E11103": { code: "E11103", domain: "admin_auth", name: "ADMIN_NOT_FOUND_OR_INACTIVE", uiMessage: "管理者アカウントが無効化されています", action: "システム管理者に連絡" },
  "E11104": { code: "E11104", domain: "admin_auth", name: "REFRESH_TOKEN_INVALID", uiMessage: "管理者セッション情報が無効です", action: "再ログインする" },
  "E11105": { code: "E11105", domain: "admin_auth", name: "REFRESH_TOKEN_REVOKED", uiMessage: "このセッションは破棄されています", action: "再ログインする" },
  "E11106": { code: "E11106", domain: "admin_auth", name: "REFRESH_DEVICE_MISMATCH", uiMessage: "セッションを開始した端末と一致しません", action: "再ログインする" },
  "E11107": { code: "E11107", domain: "admin_auth", name: "REFRESH_TOKEN_EXPIRED", uiMessage: "セッションの有効期限が切れています", action: "再ログインする" },
  "E12100": { code: "E12100", domain: "master", name: "MASTER_NOT_FOUND", uiMessage: "マスターデータが取得できません", action: "再読み込み" },
  "E12101": { code: "E12101", domain: "master", name: "MASTER_KEY_INVALID", uiMessage: "無効なマスターキーが指定されました", action: "一覧に戻る" },
} as const satisfies Record<string, ErrorCodeDefinition>;

export type ErrorCodeValue = keyof typeof ERROR_DEFINITIONS;

export const ERROR_CODE_LIST: readonly ErrorCodeDefinition[] = Object.values(ERROR_DEFINITIONS);

export function getErrorDefinition(code: string): ErrorCodeDefinition | undefined {
  return ERROR_DEFINITIONS[code as ErrorCodeValue];
}

export function requireErrorDefinition(code: string): ErrorCodeDefinition {
  const found = getErrorDefinition(code);
  if (!found) {
    throw new Error(`Unknown error code: ${code}`);
  }
  return found;
}

export function isErrorWithCode(value: unknown): value is { error: { code: string } } {
  if (!value || typeof value !== 'object') return false;
  const error = (value as any).error;
  return !!error && typeof error === 'object' && typeof error.code === 'string';
}

export function resolveUiError(code: string): { uiMessage: string; action: string | null } | undefined {
  const def = getErrorDefinition(code);
  if (!def) return undefined;
  return { uiMessage: def.uiMessage, action: def.action };
}

