/* eslint-disable */
// Code generated by scripts/generateErrorCodes.ts. DO NOT EDIT.
// Run `npm run generate:error-codes` after editing error_codes.yaml.

export interface ErrorCodeDefinition {
  code: string;
  domain: string;
  name: string;
  uiMessage: string;
  action: string | null;
}

export const ERROR_DEFINITIONS = {
  "E00100": { code: "E00100", domain: "common", name: "UNAUTHENTICATED", uiMessage: "ログインが必要です", action: "ログインする" },
  "E00101": { code: "E00101", domain: "common", name: "PERMISSION_DENIED", uiMessage: "アクセス権限がありません", action: "トップに戻る" },
  "E00102": { code: "E00102", domain: "common", name: "VALIDATION_ERROR", uiMessage: "入力内容を確認してください", action: "入力を修正する" },
  "E00103": { code: "E00103", domain: "common", name: "RESOURCE_NOT_FOUND", uiMessage: "データが見つかりません", action: "トップに戻る" },
  "E00104": { code: "E00104", domain: "common", name: "CONFLICT", uiMessage: "操作が競合しました。再度お試しください", action: "再度お試しください" },
  "E00999": { code: "E00999", domain: "common", name: "UNEXPECTED_ERROR", uiMessage: "予期しないエラーが発生しました", action: "再度お試しください" },
  "E021": { code: "E021", domain: "diagnostics", name: "INVALID_PAYLOAD", uiMessage: "回答の送信内容が不正です", action: "入力を見直す" },
  "E022": { code: "E022", domain: "diagnostics", name: "OPTION_OUT_OF_VERSION", uiMessage: "設問が更新されました。フォームを再読み込みしてください", action: "フォームを再取得" },
  "E040": { code: "E040", domain: "diagnostics", name: "SESSION_NOT_FOUND", uiMessage: "診断セッションが見つかりません。最初からやり直してください", action: "診断を再開する" },
  "E041": { code: "E041", domain: "diagnostics", name: "DUPLICATE_ANSWER", uiMessage: "この選択肢は既に送信済みです", action: "結果を確認する" },
  "E062": { code: "E062", domain: "diagnostics", name: "INVALID_SESSION_CODE", uiMessage: "診断セッションの形式が正しくありません", action: "再度お試しください" },
  "E063": { code: "E063", domain: "diagnostics", name: "SESSION_OWNED_BY_OTHER", uiMessage: "この診断結果は別のアカウントに保存されています", action: "別のアカウントを確認してください" },
  "E043": { code: "E043", domain: "diagnostics", name: "SYSTEM_PROMPT_MISSING", uiMessage: "診断の設定が不完全なため結果を生成できません", action: "時間をおいて再度お試しください" },
  "E044": { code: "E044", domain: "diagnostics", name: "LLM_OP_INCOMPLETE", uiMessage: "選択肢情報が不足しているため結果を生成できません", action: "回答を再送信してください" },
  "E045": { code: "E045", domain: "diagnostics", name: "NO_ANSWERS", uiMessage: "回答が不足しているため結果を生成できません", action: "必要な設問に回答する" },
  "E050": { code: "E050", domain: "diagnostics", name: "LLM_CALL_FAILED", uiMessage: "結果の生成に失敗しました。時間をおいて再度お試しください", action: "再実行する" },
  "E10100": { code: "E10100", domain: "auth", name: "EMAIL_ALREADY_REGISTERED", uiMessage: "このメールアドレスはすでに登録されています", action: "ログインする" },
  "E10101": { code: "E10101", domain: "auth", name: "INVALID_CREDENTIALS", uiMessage: "メールアドレスまたはパスワードが正しくありません", action: "入力を確認する" },
  "E10102": { code: "E10102", domain: "auth", name: "GITHUB_NOT_CONFIGURED", uiMessage: "現在 GitHub ログインを利用できません", action: "通常ログインを試す" },
  "E10103": { code: "E10103", domain: "auth", name: "GITHUB_CODE_REQUIRED", uiMessage: "GitHub 認証コードを入力してください", action: "やり直す" },
  "E10104": { code: "E10104", domain: "auth", name: "GITHUB_TOKEN_MISSING", uiMessage: "GitHub トークンの取得に失敗しました", action: "再試行する" },
  "E10105": { code: "E10105", domain: "auth", name: "GITHUB_USER_FETCH_FAILED", uiMessage: "GitHub ユーザー情報の取得に失敗しました", action: "時間をおいて再実行" },
  "E10106": { code: "E10106", domain: "auth", name: "GITHUB_OAUTH_ERROR", uiMessage: "GitHub 連携中にエラーが発生しました", action: "ログイン方法を選び直す" },
  "E10107": { code: "E10107", domain: "auth", name: "GITHUB_USER_ID_MISSING", uiMessage: "GitHub ユーザー情報に ID が含まれていません", action: "サポートに連絡する" },
  "E10108": { code: "E10108", domain: "auth", name: "GITHUB_EMAIL_REQUIRED", uiMessage: "GitHub の確認済みメールアドレスが必要です", action: "GitHub 設定を確認する" },
  "E10109": { code: "E10109", domain: "auth", name: "INVALID_REFRESH_TOKEN", uiMessage: "セッションの有効期限が切れています", action: "再ログインする" },
  "E10110": { code: "E10110", domain: "auth", name: "REFRESH_TOKEN_REVOKED", uiMessage: "セッションが無効化されました", action: "再ログインする" },
  "E10111": { code: "E10111", domain: "auth", name: "REFRESH_DEVICE_MISMATCH", uiMessage: "別の端末からのアクセスが検出されました", action: "同じ端末で再試行" },
  "E10112": { code: "E10112", domain: "auth", name: "REFRESH_TOKEN_EXPIRED", uiMessage: "セッションの有効期限が切れました", action: "再ログインする" },
  "E10113": { code: "E10113", domain: "auth", name: "USER_NOT_FOUND", uiMessage: "アカウントが見つかりません", action: "登録情報を確認する" },
  "E10114": { code: "E10114", domain: "auth", name: "INVALID_TOKEN", uiMessage: "ログイン状態が一致しません", action: "再ログインする" },
  "E11100": { code: "E11100", domain: "admin_auth", name: "INVALID_ADMIN_CREDENTIALS", uiMessage: "管理者 ID またはパスワードが正しくありません", action: "入力を確認する" },
  "E11101": { code: "E11101", domain: "admin_auth", name: "ADMIN_TOKEN_INVALID", uiMessage: "管理者セッションが無効です", action: "再ログインする" },
  "E11102": { code: "E11102", domain: "admin_auth", name: "ADMIN_TOKEN_SCOPE_INVALID", uiMessage: "管理者権限が不足しています", action: "トップに戻る" },
  "E11103": { code: "E11103", domain: "admin_auth", name: "ADMIN_NOT_FOUND_OR_INACTIVE", uiMessage: "管理者アカウントが無効化されています", action: "システム管理者に連絡" },
  "E12100": { code: "E12100", domain: "master", name: "MASTER_NOT_FOUND", uiMessage: "マスターデータが見つかりません", action: "再読み込みする" },
  "E12101": { code: "E12101", domain: "master", name: "MASTER_KEY_INVALID", uiMessage: "指定したマスターキーは利用できません", action: "トップに戻る" },
} as const satisfies Record<string, ErrorCodeDefinition>;

export type ErrorCodeValue = keyof typeof ERROR_DEFINITIONS;

export const ERROR_CODE_LIST: readonly ErrorCodeDefinition[] = Object.values(ERROR_DEFINITIONS);

export function getErrorDefinition(code: string): ErrorCodeDefinition | undefined {
  return ERROR_DEFINITIONS[code as ErrorCodeValue];
}

export function requireErrorDefinition(code: string): ErrorCodeDefinition {
  const found = getErrorDefinition(code);
  if (!found) {
    throw new Error(`Unknown error code: ${code}`);
  }
  return found;
}

export function isErrorWithCode(value: unknown): value is { error: { code: string } } {
  if (!value || typeof value !== 'object') return false;
  const error = (value as any).error;
  return !!error && typeof error === 'object' && typeof error.code === 'string';
}

export function resolveUiError(code: string): { uiMessage: string; action: string | null } | undefined {
  const def = getErrorDefinition(code);
  if (!def) return undefined;
  return { uiMessage: def.uiMessage, action: def.action };
}
