# Code generated by scripts/generate_error_codes.py. DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Final


@dataclass(frozen=True)
class ErrorDefinition:
    """Static metadata for an application error code."""
    code: str
    domain: str
    name: str
    http_status: int
    message: str


class ErrorCode(str, Enum):
    """Enumerates all application error codes."""
    DIAGNOSTICS_DIAGNOSTIC_NOT_FOUND = "E001"
    COMMON_UNAUTHENTICATED = "E00100"
    COMMON_PERMISSION_DENIED = "E00101"
    COMMON_VALIDATION_ERROR = "E00102"
    COMMON_RESOURCE_NOT_FOUND = "E00103"
    DIAGNOSTICS_VERSION_NAME_DUP = "E002"
    COMMON_UNEXPECTED_ERROR = "E00999"
    DIAGNOSTICS_VERSION_NOT_FOUND = "E010"
    DIAGNOSTICS_STATUS_INVALID = "E011"
    DIAGNOSTICS_LIMIT_INVALID = "E012"
    DIAGNOSTICS_INVALID_FILTER = "E013"
    DIAGNOSTICS_VERSION_FROZEN = "E020"
    DIAGNOSTICS_INVALID_PAYLOAD = "E021"
    DIAGNOSTICS_OPTION_OUT_OF_VERSION = "E022"
    DIAGNOSTICS_DEP_MISSING = "E030"
    DIAGNOSTICS_IMPORT_VALIDATION = "E031"
    DIAGNOSTICS_SHEET_MISSING = "E033"
    DIAGNOSTICS_COL_MISSING = "E034"
    DIAGNOSTICS_SESSION_NOT_FOUND = "E040"
    DIAGNOSTICS_DUPLICATE_ANSWER = "E041"
    DIAGNOSTICS_SYSTEM_PROMPT_MISSING = "E043"
    DIAGNOSTICS_LLM_OP_INCOMPLETE = "E044"
    DIAGNOSTICS_NO_ANSWERS = "E045"
    DIAGNOSTICS_LLM_CALL_FAILED = "E050"
    DIAGNOSTICS_INVALID_SESSION_CODE = "E062"
    DIAGNOSTICS_SESSION_OWNED_BY_OTHER = "E063"
    AUTH_EMAIL_ALREADY_REGISTERED = "E10100"
    AUTH_INVALID_CREDENTIALS = "E10101"
    AUTH_GITHUB_NOT_CONFIGURED = "E10102"
    AUTH_GITHUB_CODE_REQUIRED = "E10103"
    AUTH_GITHUB_TOKEN_MISSING = "E10104"
    AUTH_GITHUB_USER_FETCH_FAILED = "E10105"
    AUTH_GITHUB_OAUTH_ERROR = "E10106"
    AUTH_GITHUB_USER_ID_MISSING = "E10107"
    AUTH_GITHUB_EMAIL_REQUIRED = "E10108"
    AUTH_INVALID_REFRESH_TOKEN = "E10109"
    AUTH_REFRESH_TOKEN_REVOKED = "E10110"
    AUTH_REFRESH_DEVICE_MISMATCH = "E10111"
    AUTH_REFRESH_TOKEN_EXPIRED = "E10112"
    AUTH_USER_NOT_FOUND = "E10113"
    AUTH_INVALID_TOKEN = "E10114"
    ADMIN_AUTH_INVALID_ADMIN_CREDENTIALS = "E11100"
    ADMIN_AUTH_ADMIN_TOKEN_INVALID = "E11101"
    ADMIN_AUTH_ADMIN_TOKEN_SCOPE_INVALID = "E11102"
    ADMIN_AUTH_ADMIN_NOT_FOUND_OR_INACTIVE = "E11103"
    MASTER_MASTER_NOT_FOUND = "E12100"
    MASTER_MASTER_KEY_INVALID = "E12101"

    def definition(self) -> ErrorDefinition:
        return ERROR_DEFINITIONS[self]

    @property
    def http_status(self) -> int:
        return self.definition().http_status

    @property
    def message(self) -> str:
        return self.definition().message

    @property
    def domain(self) -> str:
        return self.definition().domain

    @property
    def label(self) -> str:
        return self.definition().name

    @classmethod
    def from_code(cls, code: str) -> "ErrorCode":
        try:
            return _ERROR_BY_VALUE[code]
        except KeyError as exc:
            raise ValueError(f'Unknown error code: {code}') from exc


ERROR_DEFINITIONS: Final[dict[ErrorCode, ErrorDefinition]] = {
    ErrorCode.DIAGNOSTICS_DIAGNOSTIC_NOT_FOUND: ErrorDefinition(code="E001", domain="diagnostics", name="DIAGNOSTIC_NOT_FOUND", http_status=404, message="指定した診断が存在しません"),
    ErrorCode.COMMON_UNAUTHENTICATED: ErrorDefinition(code="E00100", domain="common", name="UNAUTHENTICATED", http_status=401, message="認証が必要です"),
    ErrorCode.COMMON_PERMISSION_DENIED: ErrorDefinition(code="E00101", domain="common", name="PERMISSION_DENIED", http_status=403, message="この操作を実行する権限がありません"),
    ErrorCode.COMMON_VALIDATION_ERROR: ErrorDefinition(code="E00102", domain="common", name="VALIDATION_ERROR", http_status=422, message="入力値が不正です"),
    ErrorCode.COMMON_RESOURCE_NOT_FOUND: ErrorDefinition(code="E00103", domain="common", name="RESOURCE_NOT_FOUND", http_status=404, message="指定されたリソースが見つかりません"),
    ErrorCode.DIAGNOSTICS_VERSION_NAME_DUP: ErrorDefinition(code="E002", domain="diagnostics", name="VERSION_NAME_DUP", http_status=409, message="同名の診断版が既に存在します"),
    ErrorCode.COMMON_UNEXPECTED_ERROR: ErrorDefinition(code="E00999", domain="common", name="UNEXPECTED_ERROR", http_status=500, message="予期しないエラーが発生しました"),
    ErrorCode.DIAGNOSTICS_VERSION_NOT_FOUND: ErrorDefinition(code="E010", domain="diagnostics", name="VERSION_NOT_FOUND", http_status=404, message="指定した診断版が存在しません"),
    ErrorCode.DIAGNOSTICS_STATUS_INVALID: ErrorDefinition(code="E011", domain="diagnostics", name="STATUS_INVALID", http_status=400, message="ステータスの指定が不正です"),
    ErrorCode.DIAGNOSTICS_LIMIT_INVALID: ErrorDefinition(code="E012", domain="diagnostics", name="LIMIT_INVALID", http_status=400, message="limit の指定が不正です"),
    ErrorCode.DIAGNOSTICS_INVALID_FILTER: ErrorDefinition(code="E013", domain="diagnostics", name="INVALID_FILTER", http_status=400, message="クエリパラメータの組み合わせが不正です"),
    ErrorCode.DIAGNOSTICS_VERSION_FROZEN: ErrorDefinition(code="E020", domain="diagnostics", name="VERSION_FROZEN", http_status=409, message="診断版は凍結されています"),
    ErrorCode.DIAGNOSTICS_INVALID_PAYLOAD: ErrorDefinition(code="E021", domain="diagnostics", name="INVALID_PAYLOAD", http_status=400, message="回答の送信内容が不正です"),
    ErrorCode.DIAGNOSTICS_OPTION_OUT_OF_VERSION: ErrorDefinition(code="E022", domain="diagnostics", name="OPTION_OUT_OF_VERSION", http_status=400, message="指定した選択肢が診断版に含まれていません"),
    ErrorCode.DIAGNOSTICS_DEP_MISSING: ErrorDefinition(code="E030", domain="diagnostics", name="DEP_MISSING", http_status=409, message="必要な依存データが不足しています"),
    ErrorCode.DIAGNOSTICS_IMPORT_VALIDATION: ErrorDefinition(code="E031", domain="diagnostics", name="IMPORT_VALIDATION", http_status=400, message="入力内容の検証に失敗しました"),
    ErrorCode.DIAGNOSTICS_SHEET_MISSING: ErrorDefinition(code="E033", domain="diagnostics", name="SHEET_MISSING", http_status=400, message="インポートテンプレに必須シートが不足しています"),
    ErrorCode.DIAGNOSTICS_COL_MISSING: ErrorDefinition(code="E034", domain="diagnostics", name="COL_MISSING", http_status=400, message="インポートテンプレの列定義が一致しません"),
    ErrorCode.DIAGNOSTICS_SESSION_NOT_FOUND: ErrorDefinition(code="E040", domain="diagnostics", name="SESSION_NOT_FOUND", http_status=404, message="指定した診断セッションが存在しません"),
    ErrorCode.DIAGNOSTICS_DUPLICATE_ANSWER: ErrorDefinition(code="E041", domain="diagnostics", name="DUPLICATE_ANSWER", http_status=409, message="同じ選択肢が既に登録されています"),
    ErrorCode.DIAGNOSTICS_SYSTEM_PROMPT_MISSING: ErrorDefinition(code="E043", domain="diagnostics", name="SYSTEM_PROMPT_MISSING", http_status=400, message="system_prompt が設定されていません"),
    ErrorCode.DIAGNOSTICS_LLM_OP_INCOMPLETE: ErrorDefinition(code="E044", domain="diagnostics", name="LLM_OP_INCOMPLETE", http_status=400, message="選択肢の llm_op が不足しています"),
    ErrorCode.DIAGNOSTICS_NO_ANSWERS: ErrorDefinition(code="E045", domain="diagnostics", name="NO_ANSWERS", http_status=400, message="回答が0件のため結果を生成できません"),
    ErrorCode.DIAGNOSTICS_LLM_CALL_FAILED: ErrorDefinition(code="E050", domain="diagnostics", name="LLM_CALL_FAILED", http_status=502, message="LLM 呼び出しに失敗しました"),
    ErrorCode.DIAGNOSTICS_INVALID_SESSION_CODE: ErrorDefinition(code="E062", domain="diagnostics", name="INVALID_SESSION_CODE", http_status=400, message="指定した診断セッションコードは利用できません"),
    ErrorCode.DIAGNOSTICS_SESSION_OWNED_BY_OTHER: ErrorDefinition(code="E063", domain="diagnostics", name="SESSION_OWNED_BY_OTHER", http_status=409, message="指定した診断セッションは既に別のユーザーに紐付けられています"),
    ErrorCode.AUTH_EMAIL_ALREADY_REGISTERED: ErrorDefinition(code="E10100", domain="auth", name="EMAIL_ALREADY_REGISTERED", http_status=400, message="メールアドレスは既に登録されています"),
    ErrorCode.AUTH_INVALID_CREDENTIALS: ErrorDefinition(code="E10101", domain="auth", name="INVALID_CREDENTIALS", http_status=401, message="メールアドレスまたはパスワードが正しくありません"),
    ErrorCode.AUTH_GITHUB_NOT_CONFIGURED: ErrorDefinition(code="E10102", domain="auth", name="GITHUB_NOT_CONFIGURED", http_status=503, message="GitHub OAuth が設定されていません"),
    ErrorCode.AUTH_GITHUB_CODE_REQUIRED: ErrorDefinition(code="E10103", domain="auth", name="GITHUB_CODE_REQUIRED", http_status=400, message="GitHub OAuth コードまたはアクセストークンが必要です"),
    ErrorCode.AUTH_GITHUB_TOKEN_MISSING: ErrorDefinition(code="E10104", domain="auth", name="GITHUB_TOKEN_MISSING", http_status=400, message="GitHub のアクセストークンを取得できませんでした"),
    ErrorCode.AUTH_GITHUB_USER_FETCH_FAILED: ErrorDefinition(code="E10105", domain="auth", name="GITHUB_USER_FETCH_FAILED", http_status=502, message="GitHub ユーザー情報の取得に失敗しました"),
    ErrorCode.AUTH_GITHUB_OAUTH_ERROR: ErrorDefinition(code="E10106", domain="auth", name="GITHUB_OAUTH_ERROR", http_status=400, message="GitHub OAuth 認証でエラーが発生しました"),
    ErrorCode.AUTH_GITHUB_USER_ID_MISSING: ErrorDefinition(code="E10107", domain="auth", name="GITHUB_USER_ID_MISSING", http_status=400, message="GitHub ユーザー ID を取得できませんでした"),
    ErrorCode.AUTH_GITHUB_EMAIL_REQUIRED: ErrorDefinition(code="E10108", domain="auth", name="GITHUB_EMAIL_REQUIRED", http_status=400, message="GitHub で確認済みのメールアドレスを取得できませんでした"),
    ErrorCode.AUTH_INVALID_REFRESH_TOKEN: ErrorDefinition(code="E10109", domain="auth", name="INVALID_REFRESH_TOKEN", http_status=401, message="指定したリフレッシュトークンは無効です"),
    ErrorCode.AUTH_REFRESH_TOKEN_REVOKED: ErrorDefinition(code="E10110", domain="auth", name="REFRESH_TOKEN_REVOKED", http_status=401, message="リフレッシュトークンは失効しています"),
    ErrorCode.AUTH_REFRESH_DEVICE_MISMATCH: ErrorDefinition(code="E10111", domain="auth", name="REFRESH_DEVICE_MISMATCH", http_status=401, message="リフレッシュトークンのデバイス情報が一致しません"),
    ErrorCode.AUTH_REFRESH_TOKEN_EXPIRED: ErrorDefinition(code="E10112", domain="auth", name="REFRESH_TOKEN_EXPIRED", http_status=401, message="リフレッシュトークンの有効期限が切れています"),
    ErrorCode.AUTH_USER_NOT_FOUND: ErrorDefinition(code="E10113", domain="auth", name="USER_NOT_FOUND", http_status=401, message="ユーザーが見つかりません"),
    ErrorCode.AUTH_INVALID_TOKEN: ErrorDefinition(code="E10114", domain="auth", name="INVALID_TOKEN", http_status=401, message="アクセストークンが無効です"),
    ErrorCode.ADMIN_AUTH_INVALID_ADMIN_CREDENTIALS: ErrorDefinition(code="E11100", domain="admin_auth", name="INVALID_ADMIN_CREDENTIALS", http_status=401, message="管理者 ID またはパスワードが正しくありません"),
    ErrorCode.ADMIN_AUTH_ADMIN_TOKEN_INVALID: ErrorDefinition(code="E11101", domain="admin_auth", name="ADMIN_TOKEN_INVALID", http_status=401, message="管理者トークンが無効です"),
    ErrorCode.ADMIN_AUTH_ADMIN_TOKEN_SCOPE_INVALID: ErrorDefinition(code="E11102", domain="admin_auth", name="ADMIN_TOKEN_SCOPE_INVALID", http_status=403, message="管理者トークンのスコープが不正です"),
    ErrorCode.ADMIN_AUTH_ADMIN_NOT_FOUND_OR_INACTIVE: ErrorDefinition(code="E11103", domain="admin_auth", name="ADMIN_NOT_FOUND_OR_INACTIVE", http_status=401, message="管理者が存在しないか無効化されています"),
    ErrorCode.MASTER_MASTER_NOT_FOUND: ErrorDefinition(code="E12100", domain="master", name="MASTER_NOT_FOUND", http_status=404, message="指定したマスターデータが存在しません"),
    ErrorCode.MASTER_MASTER_KEY_INVALID: ErrorDefinition(code="E12101", domain="master", name="MASTER_KEY_INVALID", http_status=403, message="指定したマスターキーは利用できません"),
}

_ERROR_BY_VALUE: Final[dict[str, ErrorCode]] = {code.value: code for code in ErrorCode}

